account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    # SignUp URL: A view to allow users to sign up (register) on the platform.
    # Name: 'signup'
    # View: SignupView
    # This URL does not require any parameters.
    path('signup/', views.SignupView.as_view(), name='signup'),

    # Login URL: A view to allow users to log in to their account.
    # Name: 'login'
    # View: LoginView
    # This URL does not require any parameters.
    path('login/', views.LoginView.as_view(), name='login'),

    # Logout URL: A view to log users out of their account.
    # Name: 'logout'
    # View: LogoutView
    # This URL does not require any parameters.
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # Forget Password URL: A view for users who have forgotten their password and want to reset it.
    # Name: 'forget-pass'
    # View: ForgetPasswordView
    # This URL does not require any parameters.
    path('foget-pass/', views.ForgetPasswordView.as_view(), name='forget-pass'),

    # Reset Password URL: A view for users to reset their password using a token.
    # Name: 'reset-password'
    # View: ResetPasswordView
    # Parameters:
    #   - uidb64: A URL-safe base64 encoded user ID
    #   - token: A password reset token for verification
    path('reset-password/<uidb64>/<token>/', views.ResetPasswordView.as_view(), name='reset-password'),

    # User Profile URL: A view to display the profile of a specific user.
    # Name: 'profile-user'
    # View: ProfileUserView
    # Parameters:
    #   - user_id: The unique ID of the user whose profile is being viewed
    path('userprofile/<int:user_id>/', views.ProfileUserView.as_view(), name='profile-user'),

    # Comment Management URL: A view for administrators to approve or delete comments.
    # Name: 'comment-management'
    # View: CommentManagementView
    # Parameters:
    #   - comment_id: The unique ID of the comment to be managed (approved or deleted)
    path('comment/action/<int:comment_id>/', views.CommentManagementView.as_view(), name='comment-management'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Home URL: A view to display the home page of the site.
    # Name: 'home'
    # View: HomeView
    # This URL does not require any parameters.
    path('', views.HomeView.as_view(), name='home'),

    # Blog Post Detail URL: A view to display a detailed view of a specific blog post.
    # Name: 'post-detail'
    # View: BlogPostDetailView
    # Parameters:
    #   - pk: The primary key (ID) of the blog post
    #   - slug: A URL-friendly slug for the blog post
    path('post-detail/<int:pk>/<slug:slug>/', views.BlogPostDetailView.as_view(), name='post-detail'),

    # Delete Comment URL: A view for users to delete a comment they have made.
    # Name: 'delete-comment'
    # View: DeleteCommentView
    # Parameters:
    #   - comment_id: The unique ID of the comment to be deleted
    path('comment/delete/<int:comment_id>/', views.DeleteCommentView.as_view(), name='delete-comment'),

    # Reply to Comment URL: A view for users to reply to a specific comment on a blog post.
    # Name: 'reply-comment'
    # View: ReplyCommentView
    # Parameters:
    #   - post_id: The ID of the blog post
    #   - comment_id: The ID of the comment to reply to
    path('comment/reply/<int:post_id>/<int:comment_id>/', views.ReplyCommentView.as_view(), name='reply-comment'),

    # Delete Reply URL: A view for users to delete a reply to a comment.
    # Name: 'delete-reply'
    # View: DeleteReplyView
    # Parameters:
    #   - reply_id: The unique ID of the reply to be deleted
    path('reply/<int:reply_id>/delete/', views.DeleteReplyView.as_view(), name='delete-reply'),

    # Like Post URL: A view for users to like a specific blog post.
    # Name: 'like-post'
    # View: LikePostView
    # Parameters:
    #   - pk: The ID of the blog post to be liked
    #   - slug: The URL-friendly slug of the blog post
    path('post/<int:pk>/<slug:slug>/like/', views.LikePostView.as_view(), name='like-post'),

    # Post Creation URL: A view for users to create a new blog post.
    # Name: 'post-creation'
    # View: PostCreationView
    # This URL does not require any parameters.
    path('post-creation/', views.PostCreationView.as_view(), name='post-creation'),

    # Post Edit URL: A view to edit an existing blog post (based on its primary key).
    # Name: 'post-creation'
    # View: PostCreationView
    # Parameters:
    #   - pk: The ID of the blog post to be edited
    path('post-creation/<int:pk>/', views.PostCreationView.as_view(), name='post-creation'),

    # Posts List URL: A view to display a list of all blog posts.
    # Name: 'posts'
    # View: PostsShowView
    # This URL does not require any parameters.
    path('posts/', views.PostsShowView.as_view(), name='posts'),

    # Delete Post URL: A view to delete a specific blog post.
    # Name: 'delete'
    # View: DeletePostView
    # Parameters:
    #   - pk: The ID of the blog post to be deleted
    path('posts/delete/<int:pk>/', views.DeletePostView.as_view(), name='delete'),
]

freeWords/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from ckeditor_uploader import urls as ckeditor_urls


# URL configurations for the project
urlpatterns = [
    # Admin panel URL, accessible at '/admin/'.
    # This includes the default Django admin site for managing the application.
    path('admin/', admin.site.urls),

    # Including URLs from the 'core' app, making the paths of 'core' available under the base URL ('').
    # The namespace 'core' is used to reverse the URLs with the specified namespace in templates and views.
    path('', include('core.urls', namespace='core')),

    # Including URLs from the 'account' app, which handles user authentication and account-related views.
    # The namespace 'account' is used for URL reversal within the 'account' app.
    path('account/', include('account.urls', namespace='account')),

    # Including URLs for CKEditor, a rich text editor used in forms. These are necessary for CKEditor functionality.
    path('cheditor/', include(ckeditor_urls)),
]

# If in DEBUG mode, serve media files (images, documents, etc.) directly.
# This is useful in development, but not for production.
# The MEDIA_URL and MEDIA_ROOT settings are used to determine where the media files are stored and accessed.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from account.models import CustomUser
from image_cropping import ImageCropField, ImageRatioField
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile


class Tag(models.Model):
    """
    Represents a Tag that can be associated with blog posts.
    Tags are used to categorize or label blog posts.
    """
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class BlogPost(models.Model):
    """
    Represents a blog post with a title, description, cover image, and associated tags.
    Includes a method for generating the absolute URL of the post.
    """
    title_heading = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, null=True, blank=True)
    title_description = models.CharField(max_length=250)
    description = RichTextUploadingField(verbose_name='Description')
    cover_image = models.ImageField(upload_to='blog/cover_image/', blank=True, null=True, verbose_name='Cover Image')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created At')
    tags = models.ManyToManyField(Tag, blank=True)


    class Meta:
        verbose_name = 'Blog Post'
        verbose_name_plural = 'BlogPosts'
        ordering = ['-created_at']

    def __str__(self):
        return self.title_heading

    def get_absolute_url(self):
        """
        Returns the absolute URL of the blog post.
        Used for generating the URL dynamically.
        """
        return reverse('core:post-detail', args=(self.id, self.slug))

    def save(self, *args, **kwargs):
        if self.cover_image:
            img = Image.open(self.cover_image)
            img = img.convert("RGB")
            img = img.copy()
            img_io = BytesIO()
            img.save(img_io, format="WEBP", quality=30, optimize=True)

        self.cover_image = InMemoryUploadedFile(
            file=img_io,
            field_name=None,
            name=self.cover_image.name.split('.')[0] + ".webp",
            content_type="image/webp",
            size=img_io.tell(),
            charset=None
        )
        super().save(*args, **kwargs)


class Comment(models.Model):
    """
    Represents a comment on a blog post.
    It can also represent a reply to another comment.
    """
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    reply = models.ForeignKey('self', null=True, blank='True', on_delete=models.CASCADE, related_name='replies')
    is_reply = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f'Comment by {self.user.full_name} on {self.post.title_heading}'

    def get_replies(self):
        return self.replies.all()


class PostLike(models.Model):
    """
    Represents a like on a blog post by a user.
    Ensures that a user can like a post only once.
    """
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='likes')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['user', 'post']

    def __str__(self):
        return f'{self.user.username} like {self.post.title_heading}'

core/forms.py
from django import forms
from .models import Comment, BlogPost


class CommentForm(forms.ModelForm):
    """
    Form for users to submit a comment on a blog post.
    It includes a content field with a styled textarea widget.
    """
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 4,}),
        }


class ReplyForm(forms.ModelForm):
    """
    Form for users to reply to an existing comment.
    Similar to CommentForm but used specifically for replies.
    """
    class Meta:
        model = Comment
        fields = ['content']


class PostCreationForm(forms.ModelForm):
    """
    Form for creating a new blog post.
    Allows admin to enter title, slug, description, cover image, and tags.
    """
    class Meta:
        model = BlogPost
        fields = ['title_heading', 'slug', 'title_description', 'description', 'cover_image', 'tags']

core/templates/core/post-creation.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.css">
    <link rel="stylesheet" href="{% static 'core/css/post-creation.css' %}">

<div class="w3-light-grey">
  <div class="w3-content w3-padding-32">
    <h2>Create a New Blog Post</h2>
    <form class="w3-container w3-card-4 w3-white w3-padding-16" method="post" enctype="multipart/form-data" action="">
      {% csrf_token %}
      <label for="id_title_heading" class="w3-text-grey"><b>Title Heading</b></label>
      <input id="id_title_heading" value="{{ post.title_heading }}" name="title_heading" class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Enter title heading...">

      <label for="id_slug" class="w3-text-grey"><b>Slug</b></label>
      <input id="id_slug" value="{{ post.slug }}" name="slug" class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Enter post slug...">

      <label for="id_title_description" class="w3-text-grey"><b>Title Description</b></label>
      <input id="id_title_description" value="{{ post.title_description }}" name="title_description" class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Enter title description...">

      <label for="id_description" class="w3-text-grey"><b>Description</b></label>
      <textarea id="id_description" name="description" class="w3-input w3-border w3-margin-bottom" rows="6" placeholder="Enter post description...">{{ post.description }} </textarea>

      <label for="id_cover_image" class="w3-text-grey"><b>Cover Image</b></label>
      <input id="id_cover_image" value="post.cover_image.url" name="cover_image" class="w3-input w3-border w3-margin-bottom" type="file" accept="image/*">

      <!-- Modal for Cropping -->
      <div id="crop-modal">
        <div id="crop-container">
          <img id="image-to-crop" src="" alt="To Crop" style="max-width: 100%;">
          <br>
          <button id="crop-button" class="w3-button w3-black w3-margin-top">Crop and Upload</button>
        </div>
      </div>

      <!-- Hidden input for cropped image -->
      <input type="file" id="cropped-image-input" name="cropped_image" style="display: none;">

      <label for="id_tags" class="w3-text-grey"><b>Tags</b></label>
      <select id="id_tags" name="tags" class="w3-select w3-border" multiple>
        {% for tag in tags %}
          <option value="{{ tag.id }}">{{ tag.name }}</option>
        {% endfor %}
      </select>
      <p class="w3-text-grey" style="font-size: 0.9em; margin-top: 5px;">* Hold the "Ctrl key" and "click" to select multiple tags.</p>

      <button type="submit" class="w3-button w3-black w3-padding-large w3-margin-top">Save Post</button>
        {% if post.id %}
      <a href="{% url 'core:delete' post.pk %}" type="submit" class="w3-button w3-red w3-padding-large w3-margin-top">DELETE</a>
        {% endif %}
    </form>
  </div>
</div>

    <script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.js"></script>
    <script src="{% static 'core/js/post-creation.js' %}"></script>
{% endblock %}

<<<<<<< HEAD
{#{% block js %}#}
{##}
{#  CKEDITOR.replace('id_description', {#}
{#    toolbar: 'full',#}
{#    height: 300,#}
{#    extraPlugins: 'uploadimage',#}
{#  });#}
{##}
{#  document.getElementById('id_cover_image').addEventListener('change', function (event) {#}
{#    const file = event.target.files[0];#}
{#    if (file) {#}
{#      const reader = new FileReader();#}
{#      reader.onload = function (e) {#}
{#        const image = document.getElementById('image-to-crop');#}
{#        image.src = e.target.result;#}
{#        document.getElementById('crop-modal').style.display = 'flex';#}
{##}
{#        const cropper = new Cropper(image, {#}
{#          aspectRatio: 7 / 2,#}
{#          viewMode: 1,#}
{#        });#}
{##}
{#        document.getElementById('crop-button').onclick = function (e) {#}
{#          e.preventDefault();#}
{#          const canvas = cropper.getCroppedCanvas();#}
{#          canvas.toBlob(function (blob) {#}
{#            // Create a new File object from the cropped image#}
{#            const croppedFile = new File([blob], 'cropped-image.jpg', { type: 'image/jpeg' });#}
{##}
{#            // Create a new FileList and assign the cropped file to it#}
{#            const dataTransfer = new DataTransfer();#}
{#            dataTransfer.items.add(croppedFile);#}
{##}
{#            // Assign the FileList to the hidden input#}
{#            const croppedImageInput = document.getElementById('cropped-image-input');#}
{#            croppedImageInput.files = dataTransfer.files;#}
{##}
{#            // Hide the modal and destroy the cropper instance#}
{#            document.getElementById('crop-modal').style.display = 'none';#}
{#            cropper.destroy();#}
{#          }, 'image/jpeg');#}
{#        };#}
{#      };#}
{#      reader.readAsDataURL(file);#}
{#    }#}
{#  });#}
{##}
{#  const titleInput = document.getElementById('id_title_heading');#}
{#  const slugInput = document.getElementById('id_slug');#}
{##}
{#  titleInput.addEventListener('input', () => {#}
{#    slugInput.value = titleInput.value.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9\-]/g, '');#}
{#  });#}
{#{% endblock %}#}
=======
<<<<<<< Updated upstream
{% block js %}

  CKEDITOR.replace('id_description', {
    toolbar: 'full',
    height: 300,
    extraPlugins: 'uploadimage',
  });

  document.getElementById('id_cover_image').addEventListener('change', function (event) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function (e) {
        const image = document.getElementById('image-to-crop');
        image.src = e.target.result;
        document.getElementById('crop-modal').style.display = 'flex';

        const cropper = new Cropper(image, {
          aspectRatio: 7 / 2,
          viewMode: 1,
        });

        document.getElementById('crop-button').onclick = function (e) {
          e.preventDefault();
          const canvas = cropper.getCroppedCanvas();
          canvas.toBlob(function (blob) {
            // Create a new File object from the cropped image
            const croppedFile = new File([blob], 'cropped-image.jpg', { type: 'image/jpeg' });

            // Create a new FileList and assign the cropped file to it
            const dataTransfer = new DataTransfer();
            dataTransfer.items.add(croppedFile);

            // Assign the FileList to the hidden input
            const croppedImageInput = document.getElementById('cropped-image-input');
            croppedImageInput.files = dataTransfer.files;

            // Hide the modal and destroy the cropper instance
            document.getElementById('crop-modal').style.display = 'none';
            cropper.destroy();
          }, 'image/jpeg');
        };
      };
      reader.readAsDataURL(file);
    }
  });

  const titleInput = document.getElementById('id_title_heading');
  const slugInput = document.getElementById('id_slug');

  titleInput.addEventListener('input', () => {
    slugInput.value = titleInput.value.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9\-]/g, '');
  });
{% endblock %}
=======
>>>>>>> Stashed changes
>>>>>>> fix/minor-bugs

core/templates/core/post-detail.html
{% extends 'base.html' %}
{% load static %}

{% block extera_header %}
    <link rel="stylesheet" href="{% static 'core/css/post-detail.css' %}">
{% endblock %}

{% block content %}
<div class="w3-content" style="max-width:1400px">
  <!-- Header -->
  <header class="w3-container w3-center w3-padding-32">
    <h1><b>FREE WORDS</b></h1>
    <p>Welcome to the blog of <span class="w3-tag">unknown</span></p>
  </header>

  <!-- Post Details -->
  <div class="w3-row">
    <div class="w3-col l8 s12">
      <div class="w3-card-4 w3-margin w3-white">
        <img src="{{ post.cover_image.url }}" alt="Nature" style="width:100%">
        <div class="w3-container">
          <h3><b>{{ post.title_heading }}</b></h3>
          <h5>{{ post.title_description }}, <span class="w3-opacity">[{{ post.created_at }}]</span></h5>
          <p><b>Likes:</b> <span class="w3-tag" id="like-count">{{ post.likes.count }}</span>  <!--| <b>Views:</b> <span id="view-count">123</span>--></p>
        </div>
        <div class="w3-container">
          <p><b>Full Article:</b></p>
          <p>{{ post.description | safe }}</p>
        </div>
        <div class="w3-container w3-padding-16">
          <div class="w3-row">
            <div class="w3-col m6 s12">
              <form action="{% url 'core:like-post' pk=post.pk slug=post.slug %}" method="post" style="display: inline-block;">
                {% csrf_token %}
                  {% if is_liked %}
                  <button class="w3-button w3-padding-large w3-white w3-border w3-button-custom" type="submit"><b>Don`t Like</b></button>
                {% else %}
                  <button class="w3-button w3-padding-large w3-white w3-border w3-button-custom" type="submit"><b>Like</b></button>
                {% endif %}
              </form>
                <button class="w3-button w3-padding-large w3-white w3-border w3-button-custom" id="share-button"><b>Share</b></button>
            </div>
            <div class="w3-col m6 s12">
              <p><span class="w3-padding-large w3-right"><b>Comments </b><span class="w3-tag">{{ post.comments.count }}</span></span></p>
            </div>
          </div>
        </div>
      </div>

      <!-- Comments Section -->
      <div class="w3-card-4 w3-margin w3-white">
        <div class="w3-container w3-padding">
          <h4><b>Add a Comment:</b></h4>

          <!-- Add Comment Form -->
          <form id="comment-form" class="w3-container" method="post">
              {% csrf_token %}
            <label for="id_content" class="w3-text"><b>Your Comment:</b></label>
            <textarea name="content" id="id_content" rows="4" class="w3-input w3-border w3-round" placeholder="Write your comment here..." required></textarea>
            <button type="submit" name="new_comment" class="w3-button w3-padding-large w3-white w3-border w3-button-custom w3-margin-top"><b>Post Comment</b></button>
          </form>
          <hr>

          <!-- Display Comments -->
          <h4><b>Comments</b></h4>
          <div id="comments-list" class="w3-container">
          {% for comment in comments %}
            {% if comment.is_reply == False and comment.is_approved == True %}
            <div class="w3-border w3-padding w3-margin-bottom">
                <p><b>{{ comment.user.full_name }}:</b> {{ comment.content }} [{{ comment.created_at }}]</p>
              <!-- Edit Button and Delete Button -->
              {% if comment.user == request.user %}
              <button class="w3-button w3-padding-small w3-white w3-border w3-button-custom" onclick="toggleEditForm({{ comment.id }})">Edit</button>
              <a href="{% url 'core:delete-comment' comment.id %}" type="submit" class="w3-button w3-padding-small w3-white w3-border w3-button-delete" onclick="deleteComment({{ comment.id }})">Delete</a>
              {% endif %}

              <!-- Reply Button -->
              <button class="w3-button w3-padding-small w3-white w3-border w3-button-custom" onclick="toggleReplyForm({{ comment.id }})">Reply</button>

              <!-- Edit Form (Hidden by Default) -->
              <form id="edit-form-{{ comment.id }}" class="w3-container" method="post" style="display: none; margin-top: 10px;">
                  {% csrf_token %}
                <textarea name="content" class="w3-input w3-border w3-round">{{ comment.content }}</textarea>
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                <button type="submit" name="edit_comment" class="w3-button w3-padding-small w3-white w3-border w3-button-custom w3-margin-top"><b>Save</b></button>
              </form>

              <!-- Reply Form (Hidden by Default) -->
                <form action="{% url 'core:reply-comment' post.id comment.id %}" id="reply-form-{{ comment.id }}" class="w3-container" method="post" style="display: none; margin-top: 10px;">
                  {% csrf_token %}
                <textarea name="content" id="id_content" class="w3-input w3-border w3-round"></textarea>
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                <button type="submit" name="edit_comment" class="w3-button w3-padding-small w3-white w3-border w3-button-custom w3-margin-top"><b>Save</b></button>
              </form>


              <!-- Display Replies -->
              {% for reply in comment.replies.all %}
              <div class="w3-reply">

                {% if reply.is_reply == True and reply.is_approved == True %}
                  <p><b>{{ reply.user.full_name }} (Reply):</b> {{ reply.content }} [{{ reply.created_at }}]
                    {% if reply.user == request.user %}
                        <button class="w3-button w3-padding-small w3-white w3-border w3-button-custom" onclick="toggleEditReplyForm({{ reply.id }})">Edit</button>
                        <a href="{% url 'core:delete-reply' reply.id %}" class="w3-button w3-padding-small w3-white w3-border w3-button-custom">Delete</a> </p>
                    {% endif %}
              {% endif %}
                  <form id="edit-reply-form-{{ reply.id }}" class="w3-container reply-form" method="post"
                        action="{% url 'core:reply-comment' post.id comment.id %}" style="display: none; margin-top: 10px;">
                        {% csrf_token %}
                        <textarea name="content" class="w3-input w3-border w3-round">{{ reply.content }}</textarea>
                        <input type="hidden" name="reply_id" value="{{ reply.id }}">
                        <button type="submit" name="edit_reply" class="w3-button w3-padding-small w3-white w3-border w3-button-custom w3-margin-top">Save</button>
                    </form>
              </div>
              {% endfor %}
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <!-- Sidebar -->
    <div class="w3-col l4">
      <!-- Popular Posts -->
      <div class="w3-card w3-margin">
        <div class="w3-container w3-padding">
          <h4>Popular Posts</h4>
        </div>
        <ul class="w3-ul w3-hoverable w3-white">
            {% for post in top_liked_posts %}
          <li class="w3-padding-16">
          <a href="{% url 'core:post-detail' post.id post.slug %}" style="text-decoration: none;">
            <img src="{{ post.cover_image.url }}" alt="Image" class="w3-left w3-margin-right" style="width:50px; height: 50px; object-fit: cover;">
            <span class="w3-large">{{ post.title_heading }}</span><br>
            <span>{{ post.title_description }}</span>
          </a>
          </li>
            {% endfor %}
        </ul>
      </div>
      <hr>

      <!-- Tags -->
      <div class="w3-card w3-margin">
        <div class="w3-container w3-padding">
          <h4>Post Tags</h4>
        </div>
        <div class="w3-container w3-white">
             <p>
                 {% for tag in post.tags.all %}
                 {% if forloop.counter == 1 %}
                 <span class="w3-tag w3-black w3-margin-bottom">{{ tag.name }}</span>
                 {% else %}
                 <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">{{ tag.name}}</span>
                 {% endif %}
                 {% endfor %}
             </p>

        </div>
      </div>
    </div>
  </div>
</div>

    <script src="{% static 'core/js/post-detail.js' %}"></script>
{% endblock %}

core/templates/core/posts.html
{% extends 'base.html' %}
{% load static %}

{% block extera_header %}
    <link rel="stylesheet" href="{% static 'core/css/posts.css' %}">
{% endblock %}

{% block content %}
<div class="w3-light-grey">

<div class="w3-content" style="max-width:1400px">

  <!-- Header -->
  <header class="w3-container w3-center w3-padding-32">
    <h1><b>FREE WORDS</b></h1>
    <p>Welcome to the blog of <span class="w3-tag">unknown</span></p>
  </header>

  <!-- Search Section -->
  <div class="w3-container w3-center search-container">
    <form action="{% url 'core:posts' %}" method="get" style="display: flex; width: 100%;">
      <input type="text" class="search-input" name="q" value="{{ query }}" placeholder="Looking for somthing?...">
      <button type="submit" class="search-button w3-button w3-padding-large w3-white w3-border w3-button-custom">Search</button>
    </form>
  </div>

  <!-- Grid for blog entries -->
<div class="blog-grid">
    <!-- Blog Content -->
  {% for o in obj %}
      <div class="w3-card-4 w3-margin w3-white">
        <img src="{{ o.cover_image.url }}" alt="Nature" style="width:100%">
        <div class="w3-container">
          <h3><b>{{ o.title_heading }}</b></h3>
          <h5>{{ o.title_description }} <span class="w3-opacity">{{ o.created_at }}</span></h5>
        </div>
        <div class="w3-container">
          <p>{{ o.description| slice:"0:150" | safe }}. . . </p>
          <div class="w3-row">
            <div class="w3-col m6 s12">
              <p><a href="{% url 'core:post-detail' o.id o.slug %}" class="w3-button w3-padding-large w3-white w3-border w3-button-custom"><b>READ MORE »</b></a>
                  {% if request.user.is_superuser %}
              <a href="{% url 'core:post-creation' o.id %}" class="w3-button w3-padding-large w3-white w3-border w3-button-custom"><b>EDIT »</b></a></p>
                  {% endif %}
            </div>
            <div class="w3-col m6 w3-hide-small">
              <p>
                <span class="w3-padding-large w3-right"><b>Comments </b><span class="w3-tag">{{ o.approved_comments }}</span></span>
                <span class="w3-padding-large w3-right"><b>Likes </b><span class="w3-tag">{{ o.like_count }}</span></span>
              </p>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
</div>
</div>
</div>
{% endblock %}